/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type CreatePool = ContractEventLog<{
  pool: string;
  productId: string;
  category: string;
  0: string;
  1: string;
  2: string;
}>;

export interface IMelandSwapFactory extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): IMelandSwapFactory;
  clone(): IMelandSwapFactory;
  methods: {};
  events: {
    CreatePool(cb?: Callback<CreatePool>): EventEmitter;
    CreatePool(options?: EventOptions, cb?: Callback<CreatePool>): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "CreatePool", cb: Callback<CreatePool>): void;
  once(
    event: "CreatePool",
    options: EventOptions,
    cb: Callback<CreatePool>
  ): void;
}
