/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type LiquidityAdded = ContractEventLog<{
  provider: string;
  erc1155Amount: string;
  erc20amount: string;
  0: string;
  1: string;
  2: string;
}>;

export interface IMelandSwapExchangePool extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): IMelandSwapExchangePool;
  clone(): IMelandSwapExchangePool;
  methods: {};
  events: {
    LiquidityAdded(cb?: Callback<LiquidityAdded>): EventEmitter;
    LiquidityAdded(
      options?: EventOptions,
      cb?: Callback<LiquidityAdded>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "LiquidityAdded", cb: Callback<LiquidityAdded>): void;
  once(
    event: "LiquidityAdded",
    options: EventOptions,
    cb: Callback<LiquidityAdded>
  ): void;
}
