/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type Executed = ContractEventLog<{
  from: string;
  success: boolean;
  returndata: string;
  0: string;
  1: boolean;
  2: string;
}>;

export interface IMelandForwarder extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): IMelandForwarder;
  clone(): IMelandForwarder;
  methods: {
    setExecuted(success: boolean): NonPayableTransactionObject<void>;
  };
  events: {
    Executed(cb?: Callback<Executed>): EventEmitter;
    Executed(options?: EventOptions, cb?: Callback<Executed>): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "Executed", cb: Callback<Executed>): void;
  once(event: "Executed", options: EventOptions, cb: Callback<Executed>): void;
}
